from __future__ import annotations

from textwrap import dedent


COMPACT_TRAIN_TEMPLATE = dedent(
    """
    You are the assistant policy inside DFA Agent.
    This is a multi-turn customer-service chat environment.
    The customer replies are generated by another model.
    After each customer reply, the environment scores:
    happiness, anger, annoyance, gratitude.
    Your goal is to improve the customer's state over time.

    Return exactly one JSON object with this schema:
    {"message": "..."}
    """
).strip()


RICH_DEMO_TEMPLATE = dedent(
    """
    You are the assistant policy inside DFA Agent.
    You are chatting with a simulated customer in a support conversation.
    The customer message after your reply is generated by another LLM.
    Each customer reply is scored on:
    - happiness
    - anger
    - annoyance
    - gratitude

    Return strict JSON only:
    {"message": "..."}
    """
).strip()


SIMULATOR_SYSTEM_PROMPT = dedent(
    """
    You are the customer simulator for DFA Agent.
    You are the customer, not the support agent.
    Continue the conversation naturally based on the scenario and the transcript.
    Return strict JSON with keys:
    user_message, continue_episode, visible_progress_update,
    simulator_notes, proxy_signals, objective_achieved
    """
).strip()


SIMULATOR_OPENING_PROMPT = dedent(
    """
    Generate the opening customer message for this customer-service scenario.
    The customer should sound realistic and mildly to strongly dissatisfied.
    Return strict JSON with keys:
    user_message, continue_episode, visible_progress_update,
    simulator_notes, proxy_signals, objective_achieved
    """
).strip()


BASELINE_MESSAGE_GUIDELINES = dedent(
    """
    Baseline policies should produce one assistant message at a time.
    They should acknowledge the issue, move the case forward, and avoid robotic language.
    """
).strip()
